
enum class CodeResponse
{
	NO_PIECE = 11,
	OPPONENT_PIECE = 12,
	YOUR_PIECE_AT_DESTINATION = 13,
	ILLEGAL_MOVEMENT = 21,
	CHECKMATE_MOVE = 31,
	LEGAL_MOVEMENT_NEXT_TURN = 42,
	LEGAL_MOVEMENT_CHECK = 41

};